[package]
name = "tunein-rs"
version = "0.1.0"
authors = ["Michał Małek <michalm@fastmail.fm>"]

[lib]
name = "tunein"
path = "src/lib.rs"

[dependencies]
xml-rs = "~0.3"

[dev-dependencies]
hyper = "~0.9"
